---
- name: Playbook to create VM in OpenShift Virtualization
  hosts: localhost
  connection: local
  vars:
    password_ocp: enterhere
    username_ocp: enterhere
    vm_name: enterhere 
  tasks:

    - name: Log in to openshift (obtain access token)
      k8s_auth:
        host: https://api.ocpbmipi.intel.demolab.com:6443
        username: "{{ username_ocp }}" 
        password: "{{ password_ocp }}"
        validate_certs: false
      register: k8s_auth_results


    - name: Start RHEL8 vm with cloud init
      kubevirt_vm:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          state: running
          wait: true
          name: "{{ vm_name }}"
          namespace: virtualization
          memory: 1024M
          cloud_init_nocloud:
            userData: |-
              #cloud-config
              users:
                - name: root
                  lock_passwd: false
                  hashed_passwd: '$1$SaltSalt$YhgRYajLPrYevs14poKBQ0'
          disks:
            - name: containerdisk
              volume:
                containerDisk:
                  image: registry.redhat.io/rhel8/rhel-guest-image
              disk:
                bus: virtio

    - name: Gather facts of the newly created vm 
      k8s_info:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        name: "{{ vm_name }}"
        namespace: virtualization
        kind: VirtualMachine
        api_version: kubevirt.io/v1alpha3
      register: vm_facts
    - debug:
        var: vm_facts
